---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: facebookloginpage
spec:
  replicas: 1
  selector:     
    matchLabels:
     app: myos
  template:
    metadata:
      labels:
        app: myos
    spec:
      containers:
      - name: login
        image: palanidocker77/facebookloginpage:v1
---
apiVersion: v1
kind: Service
metadata:
  name: facebookloginpage
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
      app: myos
